### ISSUE TITLE
The question about loss function

### ISSUE THREAD

**Issue by SYH0568** [ChunML/ssd-tf2#15]
I have a question why you need  to add L2_loss into loss, instead of only adding conf_loss and loc_loss?

**Comment by ChunML** [comment]
In the paper, the author mentioned the regularization loss like below:

> We fine-tune the resulting model using SGD with initial learning rate 10−3, 0.9 momentum, 0.0005 weight decay, and batch size 32

That's the reason why.

**Comment by SYH0568** [comment]
Thanks for your answer. But I still have a question. 
How can I use the file in logs to draw a graph.
I found some information on the internet that I should write the command$ tensorboard --logdir='logs/' 
But I get  strange message and I couldn't connect to the link http://localhost:6006/.
Perhaps you can give me some advise, thank you.
Here is the message I get
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 65, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 125, in get_dynamic_plugins
    "tensorboard_plugins"
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 124, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points(
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (grpcio 1.24.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('grpcio>=1.24.3'))
